package io.logic.gson;

/**
 * A shim for {@link com.google.gson.TypeAdapterFactory} to avoid service configuration file conflicts between the
 * factories generated by the io.logic annotation processor and the annotation processor for
 * {@link org.immutables.gson.Gson.TypeAdapters}.
 * <p>
 * {@link javax.annotation.processing.Filer} does not allow for annotation processors to modify files created by other
 * annotation processors.
 * <p>
 * The annotation processor responsible for {@link org.immutables.gson.Gson.TypeAdapters} creates a service configuration
 * file that lists all the generated {@link com.google.gson.TypeAdapterFactory}.
 * <p>
 * However, the io.logic annotation processor creates custom {@link com.google.gson.TypeAdapterFactory} that also need to
 * be registered in a service configuration file.
 * <p>
 * All generated {@link com.google.gson.TypeAdapterFactory} by the io.logic annotation processor will extend
 * {@link TypeAdapterFactory} to be placed in a separate service configuration file. Otherwise, the annotation processors
 * which ran last to create their service configuration file would win and overwrite the existing file.
 *
 * @author Ian Caffey
 * @since 1.0
 */
public interface TypeAdapterFactory extends com.google.gson.TypeAdapterFactory {
}
